"""SQLAlchemy models registry for CuraReach 360"""
from app.core.database import Base
from app.models.user import User, PatientProfile, CommunityWorkerProfile
from app.models.hospital import Hospital, HospitalDepartment, HospitalService, AppointmentSlot
from app.models.case import ClinicalCase, CaseStatus, UrgencyLevel, ConsentRecord, SymptomSubmission, UploadedImage
from app.models.clinical import TriageAssessment, ClinicianReview, ReviewAction
from app.models.referral import Referral, ReferralStatus, ReferralResponse, Appointment, AppointmentStatus, FacilityRecommendation
from app.models.care_rescue import FollowUpTask, TaskStatus, Notification
from app.models.billing import SubscriptionPlan, OrganizationSubscription, DemoInvoice
from app.models.audit import CaseStatusEvent, AgentExecution, AuditLog
from app.models.medical_history import (
    PatientCondition,
    PatientAllergy,
    PatientSurgery,
    PatientMedication,
    FamilyMedicalHistory,
)
from app.models.medical_records import (
    MedicalRecord,
    MedicalRecordType,
    Prescription,
    PrescriptionItem,
)
from app.models.treatment_billing import (
    PatientTreatmentTransaction,
    TransactionType,
    PaymentStatus,
    PaymentMethod,
)

from app.models.lifelink import (
    DonorProfile,
    DonorStatus,
    HospitalVerificationStatus,
    DonationCategory,
    DonationPreference,
    DonorAvailability,
    DonorConsent,
    DonorConsentEvent,
    HospitalDonorRequest,
    DonorRequestStatus,
    DonorRequestInvitation,
    InvitationStatus,
    DonorResponse,
    AuthorizedIntroduction,
    IntroductionStatus,
    IntroductionAccessEvent,
    DonorCoordinationEvent,
    DonorReferral,
    DonorReferralStatus,
    DonorAuditEvent,
    LifeLinkSubscriptionPlan,
    HospitalLifeLinkSubscription,
    LifeLinkSubscriptionInvoice,
    LifeLinkSubscriptionStatus,
    BackgroundJob,
)

__all__ = [
    "Base",
    "User",
    "PatientProfile",
    "CommunityWorkerProfile",
    "Hospital",
    "HospitalDepartment",
    "HospitalService",
    "AppointmentSlot",
    "ClinicalCase",
    "CaseStatus",
    "UrgencyLevel",
    "ConsentRecord",
    "SymptomSubmission",
    "UploadedImage",
    "TriageAssessment",
    "ClinicianReview",
    "ReviewAction",
    "Referral",
    "ReferralStatus",
    "ReferralResponse",
    "Appointment",
    "AppointmentStatus",
    "FacilityRecommendation",
    "FollowUpTask",
    "TaskStatus",
    "Notification",
    "SubscriptionPlan",
    "OrganizationSubscription",
    "DemoInvoice",
    "CaseStatusEvent",
    "AgentExecution",
    "AuditLog",
    "PatientCondition",
    "PatientAllergy",
    "PatientSurgery",
    "PatientMedication",
    "FamilyMedicalHistory",
    "MedicalRecord",
    "MedicalRecordType",
    "Prescription",
    "PrescriptionItem",
    "PatientTreatmentTransaction",
    "TransactionType",
    "PaymentStatus",
    "PaymentMethod",
    "DonorProfile",
    "DonorStatus",
    "HospitalVerificationStatus",
    "DonationCategory",
    "DonationPreference",
    "DonorAvailability",
    "DonorConsent",
    "DonorConsentEvent",
    "HospitalDonorRequest",
    "DonorRequestStatus",
    "DonorRequestInvitation",
    "InvitationStatus",
    "DonorResponse",
    "AuthorizedIntroduction",
    "IntroductionStatus",
    "IntroductionAccessEvent",
    "DonorCoordinationEvent",
    "DonorReferral",
    "DonorReferralStatus",
    "DonorAuditEvent",
    "LifeLinkSubscriptionPlan",
    "HospitalLifeLinkSubscription",
    "LifeLinkSubscriptionInvoice",
    "LifeLinkSubscriptionStatus",
    "BackgroundJob",
]

